apiVersion: v1
kind: Pod
metadata:
  name: lightbulb-api.gunnebo.se
  labels:
    app: lightbulb-api
spec:
  containers:
  - name: lightbulb-api
    image: 675868458804.dkr.ecr.eu-west-1.amazonaws.com/lightbulb-api
    env:
    - name: ENDPOINT
      valueFrom:
        secretKeyRef:
          name: aws-endpoint
          key: endpoint
    - name: ID
      valueFrom:
        secretKeyRef:
          name: aws-admin-user
          key: id
    - name: KEY
      valueFrom:
        secretKeyRef:
          name: aws-admin-user
          key: key
    ports:
    - name: api-port
      containerPort: 8070